DROP DATABASE IF EXISTS greatBaeDB;

CREATE DATABASE greatBaeDB;

USE greatBaeDB;

CREATE TABLE items (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  itemName VARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NOT NULL
);

SELECT * FROM items;
